# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dvr/ui/template/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 857)
        self.CentralWidget = QtWidgets.QWidget(MainWindow)
        self.CentralWidget.setObjectName("CentralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.CentralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1121, 781))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.MainLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.Ch1 = QClickableLabel(self.gridLayoutWidget)
        self.Ch1.setText("")
        self.Ch1.setObjectName("Ch1")
        self.MainLayout.addWidget(self.Ch1, 0, 0, 1, 1)
        self.Ch2 = QClickableLabel(self.gridLayoutWidget)
        self.Ch2.setText("")
        self.Ch2.setObjectName("Ch2")
        self.MainLayout.addWidget(self.Ch2, 0, 1, 1, 1)
        self.Ch3 = QClickableLabel(self.gridLayoutWidget)
        self.Ch3.setText("")
        self.Ch3.setObjectName("Ch3")
        self.MainLayout.addWidget(self.Ch3, 1, 0, 1, 1)
        self.Ch4 = QClickableLabel(self.gridLayoutWidget)
        self.Ch4.setText("")
        self.Ch4.setObjectName("Ch4")
        self.MainLayout.addWidget(self.Ch4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.CentralWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1161, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

from .QClickableLabel import QClickableLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
